version: '3.8'
services:
  web-app:
    build: . 
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=mysecretpassword
      - POSTGRES_DB=postgres
      - POSTGRES_HOST=db 
    ports:
      - "5000:5000"
    networks:
      - webnet
      - dbnet 
    depends_on:
      - db  
  db:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=mysecretpassword
      - POSTGRES_DB=postgres
    ports:
      - '5432:5432'  
    networks:
      - dbnet 
networks:
  webnet:
    driver: bridge 
  dbnet:
    driver: bridge